### ISSUE TITLE
_runfinsql.exe returns ODBC error

### ISSUE THREAD

**Issue by richardrobberse** [Koubek/nav-docker-examples#1]
I've followed your instructions and started my container with the run.ps1 in nav-docker-examples-master\local_cside
RTC/Webclient works but finsql is returning the following error:
![odbc error](https://user-images.githubusercontent.com/29714289/30806883-ca2ec15e-a1f7-11e7-9e40-d6a52c2546f2.png)

Any ideas?

**Comment by Koubek** [comment]
Hi, you can find [this link](https://community.dynamics.com/nav/b/tharangacnavblog/archive/2016/08/16/data-source-name-not-found-and-no-default-driver-specified-state-id-im002-dynamics-nav).

Just to mention I have no NAV client installed on my PC right now but before I started with NAV on Docker I had installed NAV installed in a common way so all required prerequisites should be present on my PC.

Please, try to install them and give me some feedback.

Thanks.

**Comment by richardrobberse** [comment]
Hey,

Thanks for the help!
I now ran the container on a machine where I also have a version of NAV installed and now it works just fine.

**Comment by Koubek** [comment]
Happy to read your feedback ;)
