### ISSUE TITLE
VS Code error loading symbols in my nav-docker container

### ISSUE THREAD

**Issue by davmac1** [Koubek/nav-docker-examples#2]
I have my NAV docker container installed with NAV-devpreview (November) and SQL Server Express. I have the VS Code Docker extension and the AL extension installed.
I get errors when I try to download symbols. I am unclear whether one of the powershell prompts needs to point to the vsix file, or there is some other problem.
launch.json
"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "launch",
			"name": "ALProject1",
			"server": "http://DEV2Server",
			"serverInstance": "NAV",
			//"tenant": "default",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}

apps.json
{
  "id": "b46ba6eb-ef7b-4d18-80d8-aea9eccb3667",
  "name": "ALProject1",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  //"compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  //"url": "",
  "url": "http://DEV2Server:8080/al-0.11.14434.vsix",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": {
    "version": "11.0.0.0",
    "locale": "W1"
  },
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}

I get the below console error log when I try to download symbols:
[2017-11-26 21:28:19.41] Using reference symbols cache path: c:\Users\dmachanick\Documents\AL\ALProject1\.alpackages
[2017-11-26 21:28:19.46] Sending request to http://dev2server:7049/NAV/dev/packages?publisher=Microsoft&appName=W1&versionText=11.0.0.0
[2017-11-26 21:28:19.57] The request for path /NAV/dev/packages?publisher=Microsoft&appName=W1&versionText=11.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2017-11-26 21:28:19.57] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application locale and version are specified in the app.json file.
Microsoft (R) AL Compiler version 0.10.15150
Copyright (C) Microsoft Corporation. All rights reserved

**Comment by Koubek** [comment]
The usual problems here are normally docker-unrelated. Anyway, please, check the following (including also those docker-related problems as well):
+ Run `ping [container_name]` (in your particular case `ping DEV2Server`). I suppose this is not the problem as the error would be something like `The remote name could not be resolved`.
+ NAV service and `launch.json` authentication method (Windows / NavUserPassword) mismatch.
+ Installed VSIX extension version must match NAV version running in the container. It happens from time to time that people install the extension for example on October release, then with November release they start a new container but they don\`t reinstall the extension for the fresh version.
+ `URL` element is not required, or at least I don\`t use it.

**Comment by davmac1** [comment]
I have all the NAV clients running - dev, Windows, and Web - it is just the VS Code that cannot connect - when I change the URL to "", I get this message:
[2017-11-28 05:40:00.38] Error: File c:\Users\dmachanick\Documents\AL\ALProject1\Default publisher_ALProject1_1.0.0.0.app does not exist
I had 2 containers - the first used Windows, but it did not allow my external Windows id, so I create the DEV2Server using userpassword.
I just removed the first container, and I think  it must have mingled some settings. I did all of this a week ago so it is all the November release.
Below is the log from DEV2Server:
PS C:\Windows\system32> New-CSideDevContainer -containerName DEV2Server -accept_eula -auth NavUserPassword -imageName microsoft/dynamics-nav:devpreview -licenseFile "C:\NAVlicenses\Sikich DEV ISV License NAV 2017 20170224.flf" -memoryLimit 3G -updateHosts
Creating Nav container DEV2Server
Using image microsoft/dynamics-nav:devpreview
Using license file C:\NAVlicenses\Sikich DEV ISV License NAV 2017 20170224.flf
NAV Version: 11.0.19097.0-W1
Generic Tag: 0.0.3.3
Creating container DEV2Server from image microsoft/dynamics-nav:devpreview
Waiting for container DEV2Server to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
......................................Ready
Create Desktop Shortcuts for DEV2Server
Nav container DEV2Server successfully created

PS C:\Windows\system32> docker logs DEV2Server
Initializing...
Hostname is DEV2Server
PublicDnsName is DEV2Server
Running Specific Image
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CRONUS]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 2E68E33A2BECD7CCFDBF0C66A00186ADB3F8BD95
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import NAV License
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.

(6869 rows affected)
Container IP Address: 172.17.211.131
Container Hostname  : DEV2Server
Container Dns Name  : DEV2Server
Web Client          : http://DEV2Server/NAV/WebClient/
Dev. Server         : http://DEV2Server
Dev. ServerInstance : NAV

Files:
http://DEV2Server:8080/al-0.11.14434.vsix

Ready for connections!

**Comment by davmac1** [comment]
It has been adding this to the log:TimeGenerated : 11/26/2017 6:38:22 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: Development
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 6226ff69-0c3c-428e-990c-214788c20081
                ServerActivityId: 7155559e-52b1-4d4e-9abe-39ec8e4b2cca
                EventTime: 11/27/2017 00:38:22
                Message <ii>Failed request -- Method:GET; Url:<ii>http://dev2se
                rver:7049/NAV/dev/packages?publisher=Microsoft&appName=US&versi
                onText=11.0.0.0&tenant=default</ii>; StatusCode:NotFound; 
                ReasonPhrase:Not Found; ResponseBody: <pi>{"Message":"No 
                published package matches the provided arguments."}</pi></ii>
                ProcessId: 2772
                Tag: 00000LY
                ThreadId: 29
                CounterInformation:

**Comment by Koubek** [comment]
Please, could you provide `docker inspect` of your container?

**Comment by davmac1** [comment]
PS C:\Windows\system32> docker inspect DEV2Server
[
    {
        "Id": "26407108a9d5f04874df5353f85e33ccf65312fc8b7db197448f4e234ba7f003",
        "Created": "2017-11-24T00:00:06.4227744Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1964,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-11-24T00:00:29.7199553Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2017-11-28T09:15:34.4001912-06:00",
                        "End": "2017-11-28T09:15:34.8943835-06:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-28T09:16:04.9139719-06:00",
                        "End": "2017-11-28T09:16:05.6335433-06:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-28T09:16:35.6711248-06:00",
                        "End": "2017-11-28T09:16:36.266153-06:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-28T09:17:06.2870636-06:00",
                        "End": "2017-11-28T09:17:06.8217716-06:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-28T09:17:36.8444251-06:00",
                        "End": "2017-11-28T09:17:37.3023325-06:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:b72e739685cf55273d16025c9894af9c016da19b42e408ccb307e0103a1ae420",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\26407108a9d5f04874df5353f85e33ccf65312fc8b7db197448f4e234ba7f003\\26
407108a9d5f04874df5353f85e33ccf65312fc8b7db197448f4e234ba7f003-json.log",
        "Name": "/DEV2Server",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "45eb4a659a150510bce1eb3eec8f7262d74d626e5b5bbe6ffa6e4a5e5384bd24"
        ],
        "HostConfig": {
            "Binds": [
                "C:\\DEMO\\Extensions\\DEV2Server\\my:C:\\Run\\my",
                "C:\\DEMO\\Extensions\\DEV2Server\\Program Files:C:\\navpfiles",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "C:\\DEMO:C:\\DEMO"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 3221225472,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\26407108a9d5f04874df5353f85e33ccf65312fc8b7db197448f4e234ba7f
003"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\demo\\extensions\\dev2server\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\demo\\extensions\\dev2server\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\demo",
                "Destination": "c:\\demo",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "DEV2Server",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AHAANQBOAEsAYwB1ADYAUgBTAHEAMQBtAGMAKwBHAEIAWQAwADkAeABKA
EEAPQA9AHwAMwAwAGQAYQBmAGIAMwBkADUAMgAxAGUAZAA0ADMANwA5ADIAZAAxAGEAZgBjADQAMQA0ADAANwBiAGUAZgA2AGEANwBlAGMAMwA1AGQAZgBiAGIANg
A4ADQAMQA2AGEANwBhAGYAMwA4AGQAMgAyAGIAOQA3ADcAYgBhADYAZgA=",
                "removePasswordKeyFile=Y",
                "auth=NavUserPassword",
                "ExitOnError=N",
                "locale=en-US",
                "licenseFile=c:\\run\\my\\license.flf",
                "username=dave",
                "enableSymbolLoading=Y",
                "passwordKeyFile=C:\\DEMO\\Extensions\\DEV2Server\\my\\aes.key",
                "accept_eula=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.11.14434.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/441cce9c-697f-4594-a483-1b0a1cfcf573",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CRONUS"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:devpreview",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "W1",
                "created": "201711091201",
                "cu": "november",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.3",
                "version": "11.0.19097.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4cad50e3b07c941300cfe129c46b81650b4d2f8646fc2271b7f56a45ac2cc13b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "4cad50e3b07c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5a64ed4eaed92b6071e4967210b88edc92cc1eb1ebc225941deb9cff6359ac3c",
                    "EndpointID": "d7953fc0692156cc4e088acb9e18e5051655622d114e1a8360c1c220e8df153b",
                    "Gateway": "172.17.208.1",
                    "IPAddress": "172.17.211.131",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:42:45:b0",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by Koubek** [comment]
I have tried the same configs you did and everything works as expected:
![image](https://user-images.githubusercontent.com/24265973/33350652-3c5538f0-d4a0-11e7-91f7-a8b81e4e7a08.png)

Actually, I think you can simplify your config files (JSON). Look at the mine:
+ **app.json**
```
{
  "id": "8ecf343b-822f-449f-8078-b359c77f0437",
  "name": "DEV2ServerALProject",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": "11.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}
```
+ **launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "My DEV Server on Docker",
            "server": "http://DEV2Server",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22
        }
    ]
}
```

You can copy + paste the mine ones as I am using the same params.

You should be able to download symbols dynamically, you don\`t need to specify `locale: W1` etc.

**Comment by davmac1** [comment]
I pasted your code - had to change the GUID to mine - then received this error:
[2017-11-28 19:03:35.89] Using reference symbols cache path: c:\Users\dmachanick\Documents\AL\ALProject1\.alpackages
[2017-11-28 19:03:35.89] Error: File c:\Users\dmachanick\Documents\AL\ALProject1\app.json does not exist
Microsoft (R) AL Compiler version 0.10.15150
Copyright (C) Microsoft Corporation. All rights reserved

error AL1017: The manifest file is not valid. 
Error: The package could not be created.

**Comment by davmac1** [comment]
The app.json file does exist at that location and is a copy of the latest version in VS Code.
looks like I am getting closer
Do I need to reboot or is this maybe a security permissions problem?

**Comment by Koubek** [comment]
No, I don\`t think you would need to reboot. Maybe we could try it using a remote session. You can try to e-mail me (you can see my private e-mail address on the profile). I suppose we could speed up the process.

**Comment by davmac1** [comment]
I emailed you - did you receive it?
I am in the USA Central time zone, but work from home, so I have extended hours.
I am also on twitter @machanick

**Comment by Koubek** [comment]
OK, I am going to close the issue. The problem has been solved. It was a version mismatch between VSCode plugin (October I think) for AL vs. Docker image version (November update).
