### ISSUE TITLE
Can not restart container created with based winauth

### ISSUE THREAD

**Issue by PleachiM** [Koubek/nav-docker-examples#3]
Script for docker container:

$hostname = "TESTWINAUTH2"
$image = "microsoft/dynamics-nav:2017-cu6-at"

```
# Create AES key to encrypt the password:
$KeyFile = "c:\my\myAES.key"
$Key = New-Object Byte[] 16   # You can use 16, 24, or 32 for AES
[Security.Cryptography.RNGCryptoServiceProvider]::Create().GetBytes($Key)
$Key | out-file $KeyFile

$passsec = Read-Host 'Input the user`s password' -AsSecureString
$passsec = ConvertFrom-SecureString $passsec -Key $Key

docker run `
    -m 2G `
    --name $hostname `
    --hostname $hostname `
    -v c:\my:c:\run\my `
    -e Accept_eula=Y `
    -e Auth=Windows `
    -e username=$env:USERNAME `
    -e securePassword=$passsec `
    -e passwordKeyFile='c:\run\my\myAES.key' `
    -e clickonce=Y `
    $image
```
Output 
```
PS C:\Windows\system32> C:\my\Winauth.ps1
Initializing...
Hostname is TESTWINAUTH2
PublicDnsName is TESTWINAUTH2
Running Specific Image
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CronusAT]
Modifying NAV Service Tier Config File for Docker
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Creating Web Site
Creating NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
Creating ClickOnce Manifest
Container IP Address: 172.17.85.176
Container Hostname  : TESTWINAUTH2
Container Dns Name  : TESTWINAUTH2
Web Client          : http://TESTWINAUTH2/NAV/WebClient/
ClickOnce Manifest  : http://TESTWINAUTH2:8080/NAV

Files:

Ready for connections!
```

The container works as expected. 
`
729c3e65b00d        microsoft/dynamics-nav:2017-cu6-at   "powershell -Comma..."   4 minutes ago       Up 4 minutes (healthy)   80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp   TESTWINAUTH2`

When I stop this container I'm not able to start/restart the container

`docker restart TESTWINAUTH2`

`Error response from daemon: Cannot restart container TESTWINAUTH2: container 729c3e65b00d060dd9c494a1c229a1b5cdb9bb399820110be55f89d5f58475a3 encountered an error during CreateContainer: failure in a Windows system call: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (0x20) extra info: {"SystemType":"Container","Name":"729c3e65b00d060dd9c494a1c229a1b5cdb9bb399820110be55f89d5f58475a3","Owner":"docker","LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\729c3e65b00d060dd9c494a1c229a1b5cdb9bb399820110be55f89d5f58475a3","Layers":[{"ID":"aaef940d-b24d-54bc-ad26-08c5cf350cab","Path":"C:\\ProgramData\\Docker\\windowsfilter\\59a71ce7ec06e74146e93cb6782af4ccf4877c31aad0c7986a301916bb1c62ec"},{"ID":"33a3a86d-68ba-539e-9e28-8a7f7877086a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f8a498fe7009f765ecd81f0e9fc4ee214ce75f50c717430a0037eae207e488c4"},{"ID":"e83ec938-d02c-529e-914c-6fc3a7d4c93a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2e0e374fbe52200534dfe47b7e203078887ce91366c9f242fc4bc9f50f111d60"},{"ID":"36ca17ba-b2c9-58c3-81af-56a1a7e7928e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dbfce553b306c8b8be8887031e9389ca6a719afb3cd46cddbc4d1e35411487fa"},{"ID":"336663ce-acc1-59f4-8bb4-0339a58133ab","Path":"C:\\ProgramData\\Docker\\windowsfilter\\377c3b0c10714a716a03e5ceb648a5c6cd829badf2a39fef0449e06ce39c1d40"},{"ID":"d1dbdcad-290d-5e3c-a924-693db1e22f8c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f4259d991baf8b925d272d47130e90398cdf7ee19c0f1f967341672ebfc9d490"},{"ID":"f4f61f3f-faf0-5668-a45b-0028a3f085eb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\595965c1385af9dab57673125db4658261bc68f7b88119057174485a707517c2"},{"ID":"3cc8e4c2-8ea1-5d6c-9bd1-6580aefbf72d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e70381b2bb9ef37e8d8903b20d42a32d121783f44fecc87602b5e5c1208725d0"},{"ID":"f1f9d90b-99de-5bbf-820a-8a2a64177618","Path":"C:\\ProgramData\\Docker\\windowsfilter\\452b25ff0f14ba104a5b31871bfc4dbcf22222cf79b7e79e5aaf646691bddfa7"},{"ID":"2b9c624a-9e12-5da6-889e-b5692639831d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a5b6a2905ad1ba722ff56b45943d56006aa8b0acb33921d644cd108583f03e6d"},{"ID":"299b8619-0d1b-50ac-9425-5fa48f2b4bb5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\be29ebf448b9e452e5000ae46be28959d36aea3b3a64aca2b789c6df4ceba49c"},{"ID":"3da1e482-3cba-54c3-a2c2-a4824e6f4cb8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\361efeb96ea3013e8412acd147fe7ab1c51614098cae089442f5f20b095fb6b9"},{"ID":"7f8e94d3-e53c-57cd-ab29-cecacb19c234","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2d1fe32cf2216e6c63b9dd879d881c352baa1bcf9838311e9a8bd499ae97be0b"},{"ID":"4d35c541-2e96-5e92-9adc-24ffe7a3e118","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d2a67fc79f7a7f7cb115e10a091d1e3358d07e4ba9c02ba784254dd336270de4"},{"ID":"f486986a-498f-51df-b71d-2f00863a25d8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9e93e265ca05940ad61915a5b7266d5556764da34dd4c58e3e552f53798d9a80"},{"ID":"b2fc46c1-84e1-5608-af09-118581847f66","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7a8347480229a522681415c2347ea3ef69902f6ce551d6c2ab5ff12ea2162214"},{"ID":"d33905b0-26ed-597f-a565-9dd9f6c853fb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\155dfda0cc49b898e6ee38aec54ad9f61259735babe4326e1b75f1110e2fda33"},{"ID":"050d3f40-cd7b-53cc-8517-b8d51232b278","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0d24a1d151f35dfa347b3e80fb55a2b9775ce80f4ba150ac7fb576afbe710146"},{"ID":"5aa6664d-0a8b-5a81-b61f-c8587a8349fc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b483301777d2065ff040286a3c24b0458459bf8913990dbcf957b76d08e6d34c"},{"ID":"5e8204d1-d8ae-5e7a-b622-2f423cb8e573","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5100d00288bd1cdb16bc1a6557d1dddf0612192712acaace13dac357d9e55c4e"},{"ID":"34455c05-c6c3-5482-a5cb-97ac71936089","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9798b38a34d9ce7e9df630cdeaef53123b745adbd8a756ad0dfb43525e1ab5ee"},{"ID":"787162ed-65d2-587e-a2d7-256dcce333b2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cd0e12c87f2f05cc841fba5a11d48ab2722c4bae4b91da9116fbf9f0e493cf19"}],"MemoryMaximumInMB":2048,"HostName":"TESTWINAUTH2","MappedDirectories":[{"HostPath":"c:\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["f428aed2-64c9-4115-866e-245587b2aa74"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\9798b38a34d9ce7e9df630cdeaef53123b745adbd8a756ad0dfb43525e1ab5ee\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}`

docker version
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Comment by Koubek** [comment]
Reading the message I suppose the container still exists (we have seen that sometimes people remove a container etc.).

But it looks like a docker problem. Please, could you try to create another one with a different name and repeat it again (docker stop, docker start).

Eventually, you could also try something similar with the base `microsoft/windowsservercore` image. Of course, you would need add some process inside because the container will stop without any job running inside. A simple PS loop should be enough. Eg:
```PowerShell
while ($true) {
  Start-Sleep -Seconds 2
  Write-Host "Working... $(Get-Date)"
}
```

Then you can try the same with this one (stop, start).

**Comment by PleachiM** [comment]
Hello,
even if I try this again it does not work. 
But when I try to use the command 

`docker start TESTWINAUTH4 -i`

I get the following error

```
C:\Users\Admin>docker start TESTWINAUTH4 -i
Initializing...
Cannot find path 'C:\run\my\myAES.key' because it does not exist.
```

**Comment by Koubek** [comment]
OK, this is a bug that came with the SecurePassword feature. It was my mistake but I sent a fix to nav-docker repo:
https://github.com/Microsoft/nav-docker/pull/92
This has been merged but the new images have not been published yet. I think Freddy is publishing today the new images. I think the fix was included since version 0.0.3.2.
Until then you can override the behavior to avoid this. This means you need to override the whole behavior which is more complex (you need to include two affected files and change the code) or you can just add something like this as near as the end of the navstart.ps1:
```PowerShell
if (!$securepassword) {
    $securepassword = ""
}
```
I would recommend adding the code to `AdditionalOutput.ps1` which is the closest script which can be overridden. In this way, you do not have to change the default behavior (copy the original script from repo, fix it, copy into your `my` folder). You just initialize the variable right before the unoptimized code is being called.

**Comment by PleachiM** [comment]
This will do the trick! I just want to say "thank you" for the repo you provided. Like it a lot.

**Comment by Koubek** [comment]
Thank you too!!!
