### ISSUE TITLE
Error creating NAV container with WinAuth and gMSA

### ISSUE THREAD

**Issue by JoergBrugman** [Koubek/nav-docker-examples#4]
I have a Hyper-V image with a domain controller (Navtrain-DC) and the domain 'navtrain.locoal' for training purposes. On this domain controller I tried to create a NAV-Docker container with gMSA. Here is always a error while creation of the container. I use Koubek's PS scripts for this.

`# Install NAV Container Helper 
Install-Module navcontainerhelper -force

# Prepare gMSA (only once)
Add-KdsRootKey –EffectiveTime ((get-date).addhours(-10)) 
New-ADGroup "DockerGMSAGroup" -GroupCategory Security -GroupScope Global -Description "Docker-Containers using gMSA"
New-ADOrganizationalUnit -Name "gMSA for Windows Containers" -DisplayName "gMSA for Windows Containers"

# Use Koubek's scripts
$hostname = "N11"
. .\gMSA\New-gMSA.ps1
New-gMSA $hostname `
    -SecGroupPath 'OU=gMSA for Windows Containers,DC=navtrain,DC=local' `
    -PrincipalsAllowedToRetrieveManagedPassword @( 'DockerGMSAGroup' )

# Create a new NAV-container 
docker run --rm `
    -e accept_eula=y `
    -e auth=Windows `
    --security-opt "credentialspec=file://$hostname.json" `
    --name $hostname `
    --hostname $hostname `
    -e folders="c:\run\my=https://github.com/tfenster/nav-docker-samples/archive/grant-user-access.zip\nav-docker-samples-grant-user-access" `
    -e DevDomain=navtrain.local `
    -e DevGroup=ALL-DEVS `
    microsoft/dynamics-nav:2018-cu3-de`

Here is the output of the script:
`Setting up folders...
Downloading https://github.com/tfenster/nav-docker-samples/archive/grant-user-access.zip to c:\run\my
Extracting file in temp folder
Moving nav-docker-samples-grant-user-access to target folder c:\run\my
Setting up folders took 2 seconds
Initializing...
Starting Container
Hostname is N11
PublicDnsName is N11
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Running additional setup..
Setting up DEV users in NAV
 - Importing ActiveDirectory PowerShell Module

Success Restart Needed Exit Code      Feature Result                           
------- -------------- ---------      --------------                           
True    No             Success        {Remote Server Administration Tools, A...
WARNING: Error initializing default drive: 'A call to SSPI failed, see inner 
exception.'.
 - Importing NAV Module
 - Gettings users from AD group ALL-DEVS
A call to SSPI failed, see inner exception.`

I've read a lot of articles on this topic in the last few days and can not find a solution! Can someone tell me what I'm doing wrong and supporting me? It is really urgent.

**Comment by Koubek** [comment]
Have you used `install-adserviceaccount` and then also `test-adserviceaccount`? Was the test successful?

https://docs.microsoft.com/en-us/powershell/module/activedirectory/install-adserviceaccount?view=winserver2012-ps
https://docs.microsoft.com/en-us/powershell/module/activedirectory/test-adserviceaccount?view=winserver2012-ps

Then I would experiment with NAV containers as the startup phase is too long. It is better to run a windowsservercore image in the interactive mode and run this inside:
```
nltest /parentdomain
nltest /query
```

Both must return non-error result.

**Comment by JoergBrugman** [comment]
I've tested with windowsservercore in interactive mode with following results:

```
nltest /parentdomain
NAVTRAIN.LOCAL. (1)
The command completed successfully

nltest /query
Flags: 0
Connection Status = 1786 0x6fa ERROR_NO_TRUST_LSA_SECRET
The command completed successfully

Install-ADServiceAccount "N11" -Force
Install-ADServiceAccount : A call to SSPI failed, see inner exception.
At line:1 char:1
+ Install-ADServiceAccount "N11" -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Install-ADServiceAccount], AuthenticationException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.Security.Authentication.AuthenticationException,Microsoft.A
   ctiveDirectory.Management.Commands.InstallADServiceAccount

```
As you can see, I got an error very early. Im using the container network "nat".

**Comment by Koubek** [comment]
Please, you can reach me using my private email address (you can find it on the profile page). Would be better to troubleshoot at least using Skype (to be able to discuss the problem).

**Comment by mightyjens** [comment]
Hi Guys,
did you manage to solve this problem?

I'm able to successfully query user groups in AD, but New-NAVServerUser keeps throwing "The security identifier (SID) could not be mapped to a valid Windows account"

The Container-Logs say "The trust relationship between this workstation and the primary domain failed."
and nltest /query throws the same "1786 0x6fa ERROR_NO_TRUST_LSA_SECRET" message like Joerg.

Thanks in advance

**Comment by Koubek** [comment]
What does return [Test-ADServiceAccount](https://docs.microsoft.com/en-us/powershell/module/activedirectory/test-adserviceaccount?view=winserver2012-ps) on your docker host?

Also you can find some details in the event log on your DC (you need to go to "Applications and Services Logs" and in one specific log related to your DC, I can't remember right now what was the name).

**Comment by mightyjens** [comment]
Hi Koubek,
thanks for your reply:

PS D:\Docker-Skripts> Test-AdServiceAccount -Identity dockerservice
-> True


When spinning up a nav container, the eventlog on the adc writes a single informational-message:

"A user retrieved the password of a gmsa"
Ein Aufrufer hat das Kennwort eines gruppenverwalteten Dienstkontos abgerufen. 
 
Objekt des gruppenverwalteten Dienstkontos: 
CN=dockerservice,CN=Managed Service Accounts,DC=xxxxxxx,DC=dom 
Aufrufer-SID: 
S-1-5-21-2510029043-1448261702-1124101983-4653 
Aufrufer-IP: 
192.168.152.88:54364



In my understanding, the container already can successfully access the AD, as i could iterate through the Group-Members in a container-pssession. But then, adding these SIDs to NAV (New-NAVServerUser) doesn't work.

**Comment by mightyjens** [comment]
Hi Koubek,
i managed to solve the problem.

I missed to name the gsma exactly like the container-name.
At the moment i startup a nav container with the matching name, New-NAVServerUser also works as expected.

Thank you!!!

**Comment by Koubek** [comment]
Yes, of course, this is a must and there is actually no workaround. Precisely for this reason, I created the function [New-gMSA](https://github.com/Koubek/nav-docker-examples/blob/master/gmsa/New-gMSA.ps1). This should create all necessary for you in one single command.
