### ISSUE TITLE
GSMA docker issue

### ISSUE THREAD

**Issue by kkshitijNetApp** [Koubek/nav-docker-examples#5]
I was able to create credSpec file but when running the container and testing the network using nltest /sc_verify:dev.onmicrosoft.com I am getting the error no logon server. when checking the event logs "The username or password is incorrect". do you have any idea how to correct this?

**Comment by Koubek** [comment]
Hi. Please, try to check the documentation around. I think over the months and years gMSA support has improved. I am currently working in a company where we don't use it anymore so I probably can't help efficiently.
